---

- name: Setup environment variables
  become: yes
  template:
    src: default.j2
    dest: /etc/default/logstash
    backup: true
  notify:
    - restart logstash

- name: Ensure Logstash service is started
  become: yes
  service:
    name: logstash
    state: started
